#!/bin/bash
# vim:ts=4:et

FILE="version.py"
VERSION="1.2.7"
REV=$(svnversion | sed -e 's/M$//' | sed -e's/^[^:]*://')

echo "Updating $FILE to revision $REV..."
echo '#/usr/bin/env python' > $FILE
echo "VERSION = '$VERSION-r$REV'" >> $FILE

