#!/bin/bash
# vim:ts=4:et

FILE="version.py"
VERSION="1.4.0"
REV=$(git rev-list --all --count)

echo "Updating $FILE to revision $REV..."
echo '#/usr/bin/env python' > $FILE
echo "VERSION = '$VERSION-s$REV'" >> $FILE

